---
version: "2"
services:
  umaine_pin_change_service:
    build: ./pinchangeserver
    ports:
     - "5000:5000"
    volumes:
     - ./pinchangeserver:/app
     
  umaine_user_service:
    build: ./userserver
    environment:
     - "DB_PASSWORD=foobar"
    ports:
     - "5001:5001"
    volumes:
     - ./userserver:/app
    depends_on:
     - mysql
     
  mysql:
    environment:
      - "MYSQL_ROOT_PASSWORD=foobar"
      - "MYSQL_DATABASE=umaine_users"
    image: mysql
     
  umaine_mainestreet_server:
    build: ./mainestreet
    ports:
     - "5002:5002"
    volumes:
     - ./mainestreet:/app
